<h2 style='color:blue;font-weight:bold;text-align:center;'>**PWSkills Assignment **<h2>

<p style='color:green;font-weight:bold'>  Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code 
to print the data types of both the variables.</p>

In [2]:
import numpy as np

list_ = [ '1' , '2' , '3' , '4' , '5' ]

array_list = np.array(object = list_)

# Print the data types of both variables
print("Data type of 'list_':", type(list_))
print("Data type of 'array_list':", type(array_list))

Data type of 'list_': <class 'list'>
Data type of 'array_list': <class 'numpy.ndarray'>


<p style='color:green;font-weight:bold'>  Q2. Write a code to print the data type of each and every element of both the variables list_ and 
arra_list.</p>

In [3]:
import numpy as np

# Creating a standard Python list
list_ = [ '1' , '2' , '3' , '4' , '5' ]

# Creating a NumPy array from the list
array_list = np.array(list_)

# Print the data type of each element in 'list_'
print("Data type of elements in 'list_':")
for element in list_:
    print(type(element))

# Print the data type of each element in 'array_list'
print("\nData type of elements in 'array_list':")
for element in array_list:
    print(element.dtype)


Data type of elements in 'list_':
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data type of elements in 'array_list':
<U1
<U1
<U1
<U1
<U1


<p style='color:green;font-weight:bold'>  Q3. Considering the following changes in the variable, array_list:</p>

array_list = np.array(object = list_, dtype = int)

Will there be any difference in the data type of the elements present in both the variables, list_ and 
arra_list? If so then print the data types of each and every element present in both the variables, list_ 
and arra_list.

Consider the below code to answer further questions:

In [6]:
import numpy as np

num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]

num_array = np.array(object = num_list)

# Print the data type of each element in 'num_list'
print("Data type of elements in 'num_list':")
for sublist in num_array:
    for element in sublist:
        print(type(element))

Data type of elements in 'num_list':
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>


<p style='color:green;font-weight:bold'>  Q4. Write a code to find the following characteristics of variable, num_array:</p>

(i)	 shape
(ii) size

In [7]:
import numpy as np

# Assuming 'num_array' is the NumPy array
num_array = np.array([[1, 2, 3], [4, 5, 6]])

# (i) Shape of 'num_array'
shape = num_array.shape
print("Shape of 'num_array':", shape)

# (ii) Size of 'num_array'
size = num_array.size
print("Size of 'num_array':", size)


Shape of 'num_array': (2, 3)
Size of 'num_array': 6


<p style='color:green;font-weight:bold'>  Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array 
creation function.</p>

In [8]:
import numpy as np

# Create a 3x3 matrix containing zeros
zero_matrix = np.zeros((3, 3))

print(zero_matrix)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


<p style='color:green;font-weight:bold'>  Q6. Create an identity matrix of shape (5,5) using numpy functions?</p>

In [9]:
import numpy as np

# Create an identity matrix of shape (5, 5)
identity_matrix = np.identity(5)

print(identity_matrix)


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
